# CALCULATING DEFORESTATION                                                                                                                                                                                                                                                        
# AUTHOR: VICTORIA SARMIENTO                                                                                                                                                                                                                                                       
# CREATED: Summer 2021-JAN 2022#                                                                                                                                                                                                                                                   
# UPDATED: JERONIMO RODRIGUEZ/ 2022 APRIL                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                   
#Necesary packages-------------------------------------------------------                                                                                                                                                                                                          
library(raster)                                                                                                                                                                                                                                                                    
library(rgdal)                                                                                                                                                                                                                                                                     
library(sp)                                                                                                                                                                                                                                                                        
library(tidyverse)                                                                                                                                                                                                                                                                 
library(furrr)                                                                                                                                                                                                                                                                     
#This needs to be converted into using gdal or terra. Not raster anymore                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
                                        # Setting working directory and temporary folder -----------------------------------------                                                                                                                                                 
path=("/storage/home/TU/tug76452/biotablero/binary/Container_tmp")                                                                                                                                                                                                                 
setwd(path)                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                   
#path=("/storage/home/TU/tug76452/biotablero/binary/outputs")                                                                                                                                                                                                                      
#setwd(path)                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                   
#Set temporary folder. Here it is key!Troop                                                                                                                                                                                                                                        
dir.create('tempfiledir')                                                                                                                                                                                                                                                          
tempdir=paste(getwd(),'tempfiledir', sep="/")                                                                                                                                                                                                                                      
rasterOptions(tmpdir=tempdir)                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                   
#1. Cargar los raster de Bosque Armonizados de Hansen ------------                                                                                                                                                                                                                 
#Estos son los raster procesados por Jeronimo usando Hansen                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                   
tiffs<-list.files('.', pattern='tif')                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
tiffs <- tiffs[c(18:22)]                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                   
r.list<-list()                                                                                                                                                                                                                                                                     
for(i in 1:(length(tiffs)-1)){                                                                                                                                                                                                                                                     
  r.list[i]<-raster(tiffs[i])                                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                   
r.list2<-list()                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                   
for(i in 2:length(tiffs)){                                                                                                                                                                                                                                                         
  r.list2[i]<-raster(tiffs[i])                                                                                                                                                                                                                                                     
}                                                                                                                                                                                                                                                                                  
r.list2 <- r.list2[-1]                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                   
r.list[[4]]                                                                                                                                                                                                                                                                        
r.list2[[4]]                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                   
floss <-function(raso, rasi){                                                                                                                                                                                                                                                      
    def <- raso-rasi                                                                                                                                                                                                                                                               
    return(def)}                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
mem_future <- 5000*1024^2 #this is toset the limit to 5GB                                                                                                                                                                                                                          
plan(multisession, workers=4)                                                                                                                                                                                                                                                      
 options(future.globals.maxSize= mem_future)                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                   
reclv <- c(1:21)                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
mult_one <- function(var1, var2)                                                                                                                                                                                                                                                   
{                                                                                                                                                                                                                                                                                  
    def <- var1*var2                                                                                                                                                                                                                                                               
    return(def)                                                                                                                                                                                                                                                                    
}                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                   
tiffs                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
namer <- map(1:length(tiffs), function(x) substr(tiffs[x], 8,11))                                                                                                                                                                                                                  
namer <- unlist(namer)                                                                                                                                                                                                                                                             
namer <- namer[-1]                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
path=("/storage/home/TU/tug76452/biotablero/binary/def_2")                                                                                                                                                                                                                         
setwd(path)      
